Got Eventual to build and run on Haiku
HaikuArchives/Eventual pull request #7
Opened 2020-01-21 05:51 UTC by emily0618

- Create build.sh that builds/installs shared libraries and apps
- Modify makefiles to link the libraries from a standard directory
- Update the screenshot in README.md
- Remove obsolete files

2020-01-21 18:14 UTC, scottmc commented
Try writing a haikuporter recipe for this and verify that it builds into a .hpkg.  You may find you need to adjust the build script to work in a recipe and standalone.

2020-01-22 00:16 UTC, owenca requested changes
@emily0618 your way works perfectly! The alternative I suggested here is just my preference.

2020-01-22 00:16 UTC, owenca commented on src/EventEditor/Makefile
> +LIBPATHS= /boot/home/config/non-packaged/lib
```suggestion
LIBPATHS= ../lib
```

2020-01-22 00:16 UTC, owenca commented on src/EventServer/Makefile
> +LIBPATHS= /boot/home/config/non-packaged/lib
```suggestion
LIBPATHS= ../lib
```

2020-01-22 00:16 UTC, owenca commented on src/PreferencesPreflet/Makefile
> +LIBPATHS= /boot/home/config/non-packaged/lib
```suggestion
LIBPATHS= ../lib
```

2020-01-22 02:23 UTC, emily0618 commented
@scottmc I will update the recipe as soon as this pull request is merged.

2020-01-22 02:45 UTC, merged

2020-01-22 05:34 UTC, emily0618 commented
Updated the [recipe](https://github.com/haikuports/haikuports/pull/4635).